### ISSUE TITLE
[Request] "next page" to go to next issue of a comic

### ISSUE THREAD

**Issue by MelanieTanaka** [scooterpsu/Comixology_Ubooquity_2#19]
Hello,
I just installed this on my ubooquity server and am wondering if there's any way to make it so when I am on the last page of an issue (say of comic "A", issue 001, last page), if instead of doing nothing, the next page button goes to the first page of the next issue (comic "A", issue 002, page 001).

All my OPDS viewers on various mobile devices do it without needing any configuration, and I am hoping to have the same experience on desktop. It really interrupts the flow of my reading so I always end up ditching the desktop and using a tablet.

Thanks,

**Comment by scooterpsu** [comment]
The built-in reader is part of Ubooquity, not my theme. You'll want to request that sort of thing on the Ubooquity forum, [here](https://ubooquity.userecho.com/).
