### ISSUE TITLE
Darkmode with CSS rules and colors

### ISSUE THREAD

**Issue by CuddleBear92** [scooterpsu/Comixology_Ubooquity_2#22]
Darkmode with CSS rules and colors.

With the default Theme, all the CSS of the publisher pages are kept as expected:
![image](https://user-images.githubusercontent.com/8496821/72553578-537bde80-3899-11ea-912a-cf8a565e6d5e.png)

One Issue with this, its all WHITE and bright.

I want a Theme variant that still loads these CSS colors and flares but is dark as a background.
While that might crash with some CSS rules people have, thats up to them to correct if they use such a theme IMO.

Really love Dark-B but i miss the colors and flare you get from each specific publisher page.
![image](https://user-images.githubusercontent.com/8496821/72553722-963db680-3899-11ea-9b1b-f5a35e172807.png)

**Comment by CuddleBear92** [comment]
Turning off the background colors of group in dark-b gives the result i want. 
Removing that line or the whole group sadly does not give me the result i want.

![image](https://user-images.githubusercontent.com/8496821/72554849-cdad6280-389b-11ea-9d57-6e359087e3d7.png)

When i remove that line or group and hard refresh, the background color is still being filled the same way.

Im just tinkering here and are a bit out of my depth with all this css ruling.

I thought the pointed too code in the image was the code related to the background color being black, but its not seemingly.

**Comment by scooterpsu** [comment]
Yeah, the only way to make dark mode apply correctly everywhere was to include the "!important" bit, which overrides the base css rules.

Stuff added via folderInfo (ie. your folder.css) should be applied last. So adding "!important" to your css _should_ make it work.

**Comment by CuddleBear92** [comment]
That did it! thanks! <3
