### ISSUE TITLE
new v2 main comic/publisher html and css example/file?

### ISSUE THREAD

**Issue by CuddleBear92** [scooterpsu/Comixology_Ubooquity_2#23]
Could we get a new v2 main comic/publisher html and css example/file?

Half the time the featured publisher doesn't load. Tried playing with it, removing uneeded parts and such and it doesnt make it better. 
These files worked fine IIRC in v1.

Thinking about it, its prob the css that needs correcting on the placement.
But having the featured publishers not loading every time is not sounding good or stable.

Attached zip of the old v1 file as ref at the bottom.
![unknown](https://user-images.githubusercontent.com/8496821/72665883-0e78b900-3a0d-11ea-99ab-14144001e6ee.png)

[Comics-publisher-html-css.zip](https://github.com/scooterpsu/Comixology_Ubooquity_2/files/4080839/Comics-publisher-html-css.zip)

**Comment by scooterpsu** [comment]
The issue is that v2 doesn't need a publisher page anymore, that's created by the skin itself. You just need to set your base comic ID in the settings json (yours is 1 from the screenshot), and it does the rest. Your publisher html is directly conflicting with the skin, causing the above

**Comment by CuddleBear92** [comment]
I see. I don't have a settings json i believe. Only jsons i find examples of is the series ones.
Could i get an example?

**Comment by scooterpsu** [comment]
Sorry, settings.js, It has to be there or the skin wouldn't be loading.

**Comment by CuddleBear92** [comment]
Ok, thanks, found it. Interesting. Really should be a wiki to cover these things :D

**Comment by scooterpsu** [comment]
I mean searching the linked forum thread has some of these answers. It's linked in on the git readme page with the bold line mentioning the settings.js . :)

**Comment by CuddleBear92** [comment]
Update! can see the .js file have been set to `var featuredPublishers=["DC Comics","Marvel","Image","IDW Publishing","Dark Horse Comics", "Vertigo"];` by default.
Yet when i deleted the html and css files in the it still doesn't load the featured frame at all. 

Also, TBH. Haven't look much at the forum as its messy and a finer set of docs or wiki entries is good to have.

But i guess its mentioned really briefly here.

![chrome_dRMrwOsuZE](https://user-images.githubusercontent.com/8496821/72666047-b5118980-3a0e-11ea-8209-c568e2a14c74.png)

**Comment by scooterpsu** [comment]
You need to set the comicsBaseID in settings.js so it knows what page _is_ your publisher page. From your screenshots, that should be 1.

var comicsBaseID=null;  should become var comicsBaseID=1; 

And sure, a better set of documentation is nice to have. But when linked to a source where people have asked the questions you have, it's nice to be able to Ctrl+F and see if there's already an answer.
