### ISSUE TITLE
Open the wiki or mirror my fork wiki and accept image pull

### ISSUE THREAD

**Issue by CuddleBear92** [scooterpsu/Comixology_Ubooquity_2#24]
Have forked and added two wiki pages to get basics nailed down for plebs.
Have it written out with screenshots uploaded on the fork.
Will send a Pull request right away with a mention to this issue.

Attached zip with the .md files for easy Import as you cant to pulls with a wiki
[Comixology_Ubooquity_2.wiki.zip](https://github.com/scooterpsu/Comixology_Ubooquity_2/files/4083269/Comixology_Ubooquity_2.wiki.zip)

https://github.com/CuddleBear92/Comixology_Ubooquity_2/wiki/Getting-Started
https://github.com/CuddleBear92/Comixology_Ubooquity_2/wiki/Screenshots

https://github.com/scooterpsu/Comixology_Ubooquity_2/pull/25

**Comment by scooterpsu** [comment]
An issue and a PR is probably overkill, both send notifications.

**Comment by CuddleBear92** [comment]
wiki pages made on your repo
