### ISSUE TITLE
White Loading animation on a black theme

### ISSUE THREAD

**Issue by CuddleBear92** [scooterpsu/Comixology_Ubooquity_2#26]
When the user is using one of the dark themes, i think its a real shame that the loading animation is a full white screen.

Would love to see this be reflected by what theme you use.

![brave_kjPCkE9U7S](https://user-images.githubusercontent.com/8496821/72686682-8a4f3000-3af7-11ea-8409-6c1320aa17ab.png)

This is handy for busy or lower powered servers that might not for-fill the request without the animation. More so for those with sensitive skin.

**Comment by scooterpsu** [comment]
It's loaded at a base level, so I don't think that's going to be possible.

**Comment by CuddleBear92** [comment]
Thats too bad. :(
No way to make it black by default either i guess?
And something like that would need a full rewrite for the white theme too.... so thats a no so.
FeelsBad

**Comment by scooterpsu** [comment]
To clarify, the animated bit is happening before it's taking the sub-themes into account. The initial one just being loaded by Ubooquity itself. So it'd be totally possible to make it look right in some cases, it'd never look right in _all_ cases. As I'm primarily a white theme user, and added the dark stuff from someone elses' pull request, it's not something I have or intend to look too far into.
