### ISSUE TITLE
support other formats for folder.jpg image files?

### ISSUE THREAD

**Issue by CuddleBear92** [scooterpsu/Comixology_Ubooquity_2#28]
Since the folder.jpg is hardcoded into the theme itself by the looks of it (not sure how to edit to what i want).

Having it accept the extensions of jpeg, webp, png, tiff, gif and bmp should cover most bases.

Not sure if this is possible, but allowing all of them at once could allow users to mix and match in whatever folders.

Personally i would do webp as it could be half the size and load even faster (even if its a split sec already).

Would atleast open doors and be more performant while giving a fallback for users that might make personal setups with different image types.

Sidenote, i guess the publisher headers and series  covers would also be hardcoded on its own places.
(know that publisher contains the line to load it, but having an universal option would be decent.)

Pretty much every browser supports webp now so it would be cool to support it.

**Comment by scooterpsu** [comment]
When I originally started making skins for Ubooquity, it only supported jpeg images as folder images. It apparently now supports png and gif. As I'm looking for folder.jpg, if you wanted to make it look for gif or png, search the themeScript.js for folder.jpg and replace it there. 

If you wanted a different format all together, I'd make a request on the Ubooquity forum, the main dev Tom is pretty quick to either take or shoot down suggestions. At a certain point I'm up against limitations of the engine itself.

I'll leave this open in-case I pick this up again in the future, but I don't intend to make this change anytime soon.

**Comment by CuddleBear92** [comment]
well supporting something like webp would a browser limit and nothing else. ubooquity already reads webp comic pages in cbz well already.

the issue comes in, if i where to change the themeScript.js file then it would be global so mixing and matching wouldnt be a thing.
It would need to be edited in such a way that it accepts multiple types of formats on its on in the js.

**Comment by scooterpsu** [comment]
That's not what I'm saying. I'm saying the folder image loading is a Ubooquity feature, not a skin feature. I'm just taking advantage of that in other scenarios. So that wouldn't make it work anywhere I'm not specifically adding it.

**Comment by CuddleBear92** [comment]
i see, i just noted that there was folder.jpg references in the theme itself here on this repo which had me a bit thrown off.

**Comment by scooterpsu** [comment]
Right, I'm using it in more places than it's normally available. But a lot of what I'm doing is limited by the engine implementation itself.

I'll be the first to tell you "I don't want to add this", but I need you to understand when I say "I _can't_ add this".
