### ISSUE TITLE
When display width is low, side scroll is used

### ISSUE THREAD

**Issue by alpe12** [scooterpsu/Comixology_Ubooquity_2#3]
When I'm on my tablet I have to remember that there is roughly one column offscreen and that I have to scroll to see it.
![image](https://user-images.githubusercontent.com/8551127/54078301-97c74700-42a4-11e9-9ff6-f21433df4294.png)
This shouldn't be needed, since with Flex it's possible to adjust the size/location of elements.

My knowledge of CSS is limited, so the closest I could get to a fix is:
![image](https://user-images.githubusercontent.com/8551127/54078356-73b83580-42a5-11e9-8849-131c5d6a8030.png)
https://pastebin.com/pM90cp5r

**Comment by scooterpsu** [comment]
The 1100px width is in a few more places than that, but I'll see what I can do about working in a better view.

I personally use an app via OPDS, so I designed the site for pretty much just desktop usage. Better mobile support is something I'd like to add later.

**Comment by scooterpsu** [comment]
Try the latest comixology.css, it should sort this out.

**Comment by alpe12** [comment]
Thanks.
