### ISSUE TITLE
Mylar Series.json Metadata Verion 1.0.1

### ISSUE THREAD

**Issue by F688** [scooterpsu/Comixology_Ubooquity_2#35]
Comixology2 does not appear to be compatible with latest Mylar generated series.json

**Comment by scooterpsu** [comment]
Do you mean the latest release, or the themeScript.js file in the repo? I'm just about to put out a new release zip, but the themeScript.js in the repo is compatible if you manually replace just that.

**Comment by F688** [comment]
thanks
