### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by Maltavius** [scooterpsu/Comixology_Ubooquity_2#36]
I've Extracted the Zip file to the Themes folder, Selected the Comixology_v2 theme in the admin part, but things aren't looking like the images.

Is there another way this theme is supposed to be installed?

Please add install and configuration instructions to the Readme.md

**Comment by scooterpsu** [comment]
https://github.com/scooterpsu/Comixology_Ubooquity_2/wiki/Getting-Started
