### ISSUE TITLE
Remove Square cover for seires 

### ISSUE THREAD

**Issue by Uplinkpro** [scooterpsu/Comixology_Ubooquity_2#37]
Is it possible to have it display just the First Books full cover instead of a generated squashed square, for publishers its working find but for comics its low resolution and looks strange.

**Comment by scooterpsu** [comment]
I think you're misunderstanding how your setup is working. 

This skin doesn't make low resolution square images, but if you're using Mylar with "Place a thumbnail (folder.jpg) into Comic Directory for each comic", it does.
